name: Release github

on:
  push:
    branches: [ main ]

jobs:

  release-github-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesWin
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.0-win.x64"
        prerelease: false
        title: "v0.3.0-win.x64"
        files: |
            src/ArcCommander/config_win/config
            publish/win-x64/arc.exe

  release-github-linux:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesLinux
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.0-linux.x64"
        prerelease: false
        title: "v0.3.0-linux.x64"
        files: |
            src/ArcCommander/config_unix/config
            publish/linux-x64/arc

  release-github-macos:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesMac
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.0-osx.x64"
        prerelease: false
        title: "v0.3.0-osx.x64"
        files: |
            src/ArcCommander/config_unix/config
            publish/osx-x64/arc