name: Release github

on:
  push:
    branches: [ main ]

jobs:

  release-github-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesWin
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.2-win.x64"
        prerelease: false
        title: "v0.3.2-win.x64"
        files: |
            src/ArcCommander/config_win/config
            publish/win-x64/arc.exe

  release-github-linux:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesLinux
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.2-linux.x64"
        prerelease: false
        title: "v0.3.2-linux.x64"
        files: |
            src/ArcCommander/config_unix/config
            publish/linux-x64/arc

  release-github-macos:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and publish
      run: dotnet fake build -t publishBinariesMac
    - name: Codesign
      env: 
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PWD: ${{ secrets.APPLE_CERTIFICATE_PWD }}    
      run: |
        echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p password build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p password build.keychain
        security import certificate.p12 -k build.keychain -P $APPLE_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password build.keychain
        security find-identity -v
        /usr/bin/codesign --force -s F1C90BA72457317906E392CB3F348F5C9FAC3821 publish/osx-x64/arc -v      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.3.2-osx.x64"
        prerelease: false
        title: "v0.3.2-osx.x64"
        files: |
            src/ArcCommander/config_unix/config
            publish/osx-x64/arc
